# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'buyFoodPro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for buyFoodPro
pod 'Masonry'
pod 'AFNetworking'
pod 'MJExtension'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'TZImagePickerController'
pod 'SDCycleScrollView'
pod 'MJRefresh'
pod 'IQKeyboardManager'
end
